const PDFDocument = require('pdfkit');

/**
 * Generate a professional proposal PDF
 */
const generateProposalPDF = (proposal, client, user) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    const colors = {
      primary: '#6366f1',
      dark: '#1e1b4b',
      gray: '#6b7280',
      light: '#f9fafb',
      border: '#e5e7eb',
    };

    // ─── HEADER ────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 100).fill(colors.dark);

    doc.fillColor('white').fontSize(24).font('Helvetica-Bold').text('PROPOSAL', 50, 30);

    doc.fontSize(10).font('Helvetica').text(proposal.title || 'Project Proposal', 50, 62);

    doc
      .fontSize(10)
      .text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 
        doc.page.width - 200, 40, { width: 150, align: 'right' });

    // ─── FROM / TO ─────────────────────────────────────────
    doc.moveDown(3);
    const startY = 120;

    doc.fillColor(colors.dark).fontSize(10).font('Helvetica-Bold').text('FROM:', 50, startY);
    doc.fillColor(colors.gray).font('Helvetica').text(user?.name || 'Freelancer', 50, startY + 15);
    doc.text(user?.email || '', 50, startY + 28);

    doc.fillColor(colors.dark).font('Helvetica-Bold').text('PREPARED FOR:', 300, startY);
    doc.fillColor(colors.gray).font('Helvetica').text(client?.name || 'Client', 300, startY + 15);
    doc.text(client?.company || '', 300, startY + 28);
    doc.text(client?.email || '', 300, startY + 41);

    // Divider
    doc.moveTo(50, startY + 65).lineTo(doc.page.width - 50, startY + 65).strokeColor(colors.border).stroke();

    // ─── SECTIONS ──────────────────────────────────────────
    let y = startY + 85;

    const addSection = (title, content) => {
      if (!content) return;
      if (y > doc.page.height - 150) { doc.addPage(); y = 50; }

      doc.fillColor(colors.primary).fontSize(13).font('Helvetica-Bold').text(title, 50, y);
      y += 20;
      doc.fillColor(colors.dark).fontSize(10).font('Helvetica');
      doc.text(content, 50, y, { width: doc.page.width - 100, lineGap: 4 });
      y += doc.heightOfString(content, { width: doc.page.width - 100, lineGap: 4 }) + 20;
    };

    if (proposal.content) {
      const { intro, understanding, scope, timeline, pricing, terms, whyMe, nextSteps } = proposal.content;
      addSection('EXECUTIVE SUMMARY', intro);
      addSection('UNDERSTANDING YOUR REQUIREMENTS', understanding);
      addSection('SCOPE OF WORK', scope);
      addSection('PROJECT TIMELINE', timeline);
      addSection('INVESTMENT', pricing);
      addSection('TERMS & CONDITIONS', terms);
      addSection('WHY CHOOSE US', whyMe);
      addSection('NEXT STEPS', nextSteps);
    } else if (proposal.fullContent) {
      doc.fillColor(colors.dark).fontSize(10).font('Helvetica').text(proposal.fullContent, 50, y, {
        width: doc.page.width - 100,
        lineGap: 4,
      });
    }

    // ─── FOOTER ────────────────────────────────────────────
    const footerY = doc.page.height - 50;
    doc.moveTo(50, footerY - 15).lineTo(doc.page.width - 50, footerY - 15).strokeColor(colors.border).stroke();
    doc.fillColor(colors.gray).fontSize(9).font('Helvetica')
      .text(`Generated by FreelanceOS • ${new Date().toLocaleDateString()}`, 50, footerY - 5, {
        align: 'center',
        width: doc.page.width - 100,
      });

    doc.end();
  });
};

/**
 * Generate Invoice PDF
 */
const generateInvoicePDF = (invoice, client, user) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    const colors = { primary: '#6366f1', dark: '#1e1b4b', gray: '#6b7280', border: '#e5e7eb' };

    // Header
    doc.rect(0, 0, doc.page.width, 100).fill(colors.dark);
    doc.fillColor('white').fontSize(28).font('Helvetica-Bold').text('INVOICE', 50, 30);
    doc.fontSize(12).font('Helvetica').text(`#${invoice.invoiceNumber}`, 50, 65);

    // Dates
    doc.text(`Issue: ${new Date(invoice.issueDate).toLocaleDateString()}`, doc.page.width - 200, 30, { width: 150, align: 'right' });
    doc.text(`Due: ${new Date(invoice.dueDate).toLocaleDateString()}`, doc.page.width - 200, 48, { width: 150, align: 'right' });

    const statusColors = { Paid: '#10b981', Overdue: '#ef4444', Pending: '#f59e0b' };
    const sc = statusColors[invoice.status] || '#6b7280';
    doc.fillColor(sc).fontSize(10).font('Helvetica-Bold')
      .text(invoice.status.toUpperCase(), doc.page.width - 200, 66, { width: 150, align: 'right' });

    // From / To
    const y0 = 120;
    doc.fillColor(colors.dark).fontSize(10).font('Helvetica-Bold').text('FROM:', 50, y0);
    doc.fillColor(colors.gray).font('Helvetica').text(user?.name || 'Freelancer', 50, y0 + 15);
    doc.text(user?.settings?.businessName || '', 50, y0 + 28);

    doc.fillColor(colors.dark).font('Helvetica-Bold').text('BILL TO:', 300, y0);
    doc.fillColor(colors.gray).font('Helvetica').text(client?.name || 'Client', 300, y0 + 15);
    doc.text(client?.company || '', 300, y0 + 28);
    doc.text(client?.email || '', 300, y0 + 41);

    // Line items table
    let y = y0 + 80;
    doc.moveTo(50, y).lineTo(doc.page.width - 50, y).strokeColor(colors.border).stroke();
    y += 10;

    doc.fillColor(colors.dark).fontSize(9).font('Helvetica-Bold');
    doc.text('DESCRIPTION', 50, y);
    doc.text('QTY', 320, y);
    doc.text('UNIT PRICE', 370, y);
    doc.text('AMOUNT', doc.page.width - 120, y);
    y += 18;
    doc.moveTo(50, y).lineTo(doc.page.width - 50, y).strokeColor(colors.border).stroke();
    y += 10;

    invoice.lineItems?.forEach((item) => {
      doc.fillColor(colors.gray).fontSize(9).font('Helvetica');
      doc.text(item.description, 50, y, { width: 260 });
      doc.text(String(item.quantity), 320, y);
      doc.text(`$${item.unitPrice.toFixed(2)}`, 370, y);
      doc.text(`$${item.amount.toFixed(2)}`, doc.page.width - 120, y);
      y += 20;
    });

    y += 10;
    doc.moveTo(50, y).lineTo(doc.page.width - 50, y).strokeColor(colors.border).stroke();
    y += 15;

    const addTotal = (label, value, bold = false) => {
      const font = bold ? 'Helvetica-Bold' : 'Helvetica';
      const color = bold ? colors.dark : colors.gray;
      doc.fillColor(color).font(font).fontSize(bold ? 11 : 9);
      doc.text(label, doc.page.width - 200, y);
      doc.text(`$${Number(value).toFixed(2)}`, doc.page.width - 120, y);
      y += 18;
    };

    addTotal('Subtotal:', invoice.subtotal);
    if (invoice.taxRate > 0) addTotal(`Tax (${invoice.taxRate}%):`, invoice.taxAmount);
    if (invoice.discount > 0) addTotal('Discount:', invoice.discount);
    addTotal('TOTAL:', invoice.total, true);

    if (invoice.notes) {
      y += 20;
      doc.fillColor(colors.dark).fontSize(10).font('Helvetica-Bold').text('Notes:', 50, y);
      doc.fillColor(colors.gray).font('Helvetica').text(invoice.notes, 50, y + 15);
    }

    const footerY = doc.page.height - 50;
    doc.moveTo(50, footerY - 15).lineTo(doc.page.width - 50, footerY - 15).strokeColor(colors.border).stroke();
    doc.fillColor(colors.gray).fontSize(9).font('Helvetica')
      .text('Thank you for your business • FreelanceOS', 50, footerY - 5, { align: 'center', width: doc.page.width - 100 });

    doc.end();
  });
};

module.exports = { generateProposalPDF, generateInvoicePDF };
